export const LIST_CONVERSATIONS_DEFAULT_LIMIT = 20
export const LIST_CONVERSATIONS_MAX_LIMIT = 50

export const SEARCH_MESSAGES_DEFAULT_LIMIT = 10
export const SEARCH_MESSAGES_MAX_LIMIT = 25
export const SEARCH_MESSAGES_QUERY_MAX_LENGTH = 200

export const TOOL_SNIPPET_MAX_LENGTH = 200
